### ISSUE TITLE
Php Error after upating.

### ISSUE THREAD

**Issue by Third-Hyperion** [caddis/facebook-count#1]
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: curl

Filename: facebook_count/pi.facebook_count.php

Line Number: 61
A PHP Error was encountered

Severity: Warning

Message: curl_setopt() expects parameter 1 to be resource, null given

Filename: facebook_count/pi.facebook_count.php

Line Number: 61

**Comment by leigeber** [comment]
Thanks for reporting, an incorrect variable snuck in there. We've published an update that should resolve the problem.

**Comment by Third-Hyperion** [comment]
Brilliant thank you very much, out of curiosity what caused the previous version to stop working?

**Comment by leigeber** [comment]
Facebook changed that particular endpoint to require oAuth so for the time being we've moved to the Graph API which is still open for the time being.
